### PR TITLE
X12: initial cut at support for the X12.17 driver.

### PR DESCRIPTION
**Pull request by guyc**
This is a preliminary implementation supporting the Switec X12.17 / VID 6606 and AX1201728SG Quad driver chip.

### CODE REVIEW

**Comment by mattmon** [comment]
Thanks, this new library is great!

It's smoother/faster than X25 and runs 8 steppers from an atmega328.

Though, with many gauges, the blocking zero call is a usability problem - serially zeroing takes too long.

Any chance you can add a function to zero all the steppers at once?

**Comment by guyc** [comment]
You might be better off with code outside of the library for that.  

The following is untested, but should be close the right solution:

First force each motor to think it is at full-scale deflection:
```
for (int i=0; i<n; i++) {
  motor[i]->currentStep = motor[i]->steps - 1;
  motor[i]->setPosition(0);
}
```
Then advance all of the motors until they reach their target of 0.
```
done = false;
while (!done) {
  done = true;
  for (int i=0; i<n; i++) {
    motor[i]->update();
    done &= motor[i]->stopped;
  }
}
```

You could run them against their top stop instead by swapping the initialisation values to currentStep=0, setPosition(motor[i]->steps-1).  That can look very cool if you move your needles to 0 at shutdown.

**Comment by mattmon** [comment]
Thank a lot for the code suggestion!

Here's what worked for me:

`#include <SwitecX12.h>

const int STEPS = 315 * 12;
const int NUM_MOTORS = 2;
const int STEP[NUM_MOTORS] = {8, 6};
const int DIR[NUM_MOTORS] = {9, 7};
const int RESET = 10;

SwitecX12 motor[2] = {
  SwitecX12(STEPS, STEP[0], DIR[0]),
  SwitecX12(STEPS, STEP[1], DIR[1])
};

void setup() {
  digitalWrite(RESET, HIGH);
  Serial.begin(9600);
  zeroAll();
}
 
void zeroAll() {
    for (int i = 0; i < NUM_MOTORS; i++) {
    motor[i].currentStep = motor[i].steps - 1;
    motor[i].setPosition(0);
  }
  bool done = false;
  while (!done) {
    done = true;
    for (int i = 0; i < NUM_MOTORS; i++) {
      motor[i].update();
      done &= motor[i].stopped;
    }
  }
}

void loop() {
  // Do Stuff...
}`

**Comment by paulnd** [comment]
@mattmon

Could you possibly share your code for driving 8 motors as I’m having difficulties?

https://github.com/clearwater/SwitecX25/issues/15

Have you been able to zero all at once?

**Pull request merged**
